/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class FrontEnd {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FrontEnd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrontEnd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_FrontEnd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FrontEnd() {
    this(SphinxBaseJNI.new_FrontEnd(), true);
  }

  public int outputSize() {
    return SphinxBaseJNI.FrontEnd_outputSize(swigCPtr, this);
  }

  public int processUtt(String spch, long nsamps, SWIGTYPE_p_p_p_mfcc_t cep_block) {
    return SphinxBaseJNI.FrontEnd_processUtt(swigCPtr, this, spch, nsamps, SWIGTYPE_p_p_p_mfcc_t.getCPtr(cep_block));
  }

}
