/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class JsgfIterator implements java.util.Iterator<JsgfRule> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JsgfIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JsgfIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_JsgfIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public JsgfIterator(SWIGTYPE_p_void ptr) {
    this(SphinxBaseJNI.new_JsgfIterator(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public JsgfRule next() {
    long cPtr = SphinxBaseJNI.JsgfIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new JsgfRule(cPtr, true);
  }

  public boolean hasNext() {
    return SphinxBaseJNI.JsgfIterator_hasNext(swigCPtr, this);
  }

}
