/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class NBestIterator implements java.util.Iterator<NBest> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NBestIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NBestIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_NBestIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public NBestIterator(SWIGTYPE_p_void ptr) {
    this(PocketSphinxJNI.new_NBestIterator(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public NBest next() {
    long cPtr = PocketSphinxJNI.NBestIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new NBest(cPtr, true);
  }

  public boolean hasNext() {
    return PocketSphinxJNI.NBestIterator_hasNext(swigCPtr, this);
  }

}
