/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class NGramModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NGramModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NGramModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_NGramModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static NGramModel fromIter(SWIGTYPE_p_void itor) {
    long cPtr = SphinxBaseJNI.NGramModel_fromIter(SWIGTYPE_p_void.getCPtr(itor));
    return (cPtr == 0) ? null : new NGramModel(cPtr, false);
  }

  public NGramModel(String path) {
    this(SphinxBaseJNI.new_NGramModel__SWIG_0(path), true);
  }

  public NGramModel(Config config, LogMath logmath, String path) {
    this(SphinxBaseJNI.new_NGramModel__SWIG_1(Config.getCPtr(config), config, LogMath.getCPtr(logmath), logmath, path), true);
  }

  public void write(String path, int ftype) {
    SphinxBaseJNI.NGramModel_write(swigCPtr, this, path, ftype);
  }

  public int strToType(String str) {
    return SphinxBaseJNI.NGramModel_strToType(swigCPtr, this, str);
  }

  public String typeToStr(int type) {
    return SphinxBaseJNI.NGramModel_typeToStr(swigCPtr, this, type);
  }

  public void casefold(int kase) {
    SphinxBaseJNI.NGramModel_casefold(swigCPtr, this, kase);
  }

  public int size() {
    return SphinxBaseJNI.NGramModel_size(swigCPtr, this);
  }

  public int addWord(String word, float weight) {
    return SphinxBaseJNI.NGramModel_addWord(swigCPtr, this, word, weight);
  }

  public int prob(String[] n) {
    return SphinxBaseJNI.NGramModel_prob(swigCPtr, this, n);
  }

}
